"""Emit deployable Terraform for the alerts.

A threshold alert maps to one or more **`dynatrace_davis_anomaly_detectors`**
resources — the modern "anomaly detector" that runs a DQL `timeseries` query
every minute and fires on a static threshold (schema `builtin:davis.anomaly-detectors`,
analyzer `StaticThresholdAnomalyDetectionAnalyzer`).

This is intentionally the same "plan -> deployable artifact" shape the pipeline
track uses: `render_alert` shows the plan, `render_detectors_tf` emits the HCL.
"""

from __future__ import annotations

import re
from typing import List

from e2d.alerts.model import (AUTO_ADAPTIVE_ANALYZER, SEASONAL_ANALYZER,
                              STATIC_ANALYZER, AlertSpec, Detector)

_ANALYZER = STATIC_ANALYZER  # backward-compatible alias


def _hcl_str(value: str) -> str:
    """Quote a value as an HCL string (queries are multi-line -> heredoc)."""
    if "\n" in value:
        return "<<-EOT\n" + value + "\nEOT"
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _resource_name(spec: AlertSpec, idx: int) -> str:
    base = re.sub(r"[^a-z0-9_]", "_", spec.name.lower()).strip("_") or "alert"
    return f"{base}_{idx}"


def _is_numeric(value: str) -> bool:
    try:
        float(str(value).strip().strip('"'))
        return True
    except ValueError:
        return False


def _detector_block(spec: AlertSpec, det: Detector, idx: int) -> str:
    title = f"{spec.name}: {det.title}"
    analyzer = det.analyzer or _ANALYZER
    auto = analyzer != STATIC_ANALYZER
    # The static analyzer's threshold must be numeric. If the source threshold was
    # dynamic (e.g. a mustache template), emit a 0 placeholder and ship the detector
    # DISABLED so the module still applies — the user sets a real value and enables
    # it. Auto-adaptive detectors need no threshold and ship enabled.
    raw = str(det.threshold).strip().strip('"')
    numeric = _is_numeric(raw)
    threshold_value = raw if numeric else "0"
    enabled = "true" if (auto or numeric) else "false"
    description = "Migrated from Elastic " + spec.source_kind
    if auto:
        description += " — auto-adaptive baseline; Davis needs ~7 days of data"
    elif not numeric:
        description += f" — DISABLED: set a real threshold (source was dynamic: {raw})"
    fields = [
        ("alertCondition", det.alert_condition),
        ("alertOnMissingData", "false"),
        ("violatingSamples", "3"),
        ("slidingWindow", "5"),
        ("dealertingSamples", "5"),
        ("query", det.query),
    ]
    if auto:
        fields.append(("numberOfSignalFluctuations", det.signal_fluctuations or "1"))
    else:
        fields.append(("threshold", threshold_value))
    inputs = "\n".join(
        f'      analyzer_input_field {{\n        key   = "{k}"\n        value = {_hcl_str(v)}\n      }}'
        for k, v in fields
    )
    sev = "warning" if det.severity == "warning" else "error"
    return f'''resource "dynatrace_davis_anomaly_detectors" "{_resource_name(spec, idx)}" {{
  title       = {_hcl_str(title)}
  description = {_hcl_str(description)}
  enabled     = {enabled}
  source      = "Davis Anomaly Detection"
  analyzer {{
    name = "{analyzer}"
    input {{
{inputs}
    }}
  }}
  event_template {{
    properties {{
      property {{
        key   = "event.type"
        value = "CUSTOM_ALERT"
      }}
      property {{
        key   = "event.name"
        value = {_hcl_str(title)}
      }}
      property {{
        key   = "dt.davis.event.severity_level"
        value = "{sev}"
      }}
    }}
  }}
  execution_settings {{
    query_offset = 1
  }}
}}'''


def render_detectors_tf(spec: AlertSpec) -> str:
    """Full Terraform module text for a single alert's detector(s)."""
    header = ("# Generated by e2d from an Elastic " + spec.source_kind + f": {spec.name}\n"
              "# Davis anomaly detectors — each runs a 1-minute DQL series and fires on a static\n"
              "# threshold. Verify the query, threshold, and dimensions before enabling in production.\n"
              "terraform {\n"
              '  required_providers {\n'
              '    dynatrace = { source = "dynatrace-oss/dynatrace" }\n'
              "  }\n}\n")
    if not spec.detectors:
        return header + "\n# (No automatic threshold could be derived — build this one by hand.)\n"
    blocks: List[str] = [_detector_block(spec, d, i) for i, d in enumerate(spec.detectors)]
    return header + "\n" + "\n\n".join(blocks) + "\n"


def has_terraform(spec: AlertSpec) -> bool:
    return bool(spec.detectors)


# --------------------------------------------------------------------------- #
# Workflow (for alerts that carry actions / chained inputs / scripted logic)
# --------------------------------------------------------------------------- #

_ACTION_MAP = {
    "email": "dynatrace.automations:send-email-action",
    "webhook": "dynatrace.automations:http-function",
    "slack": "dynatrace.automations:http-function",
    "index": "dynatrace.automations:run-javascript",
    "unknown": "dynatrace.automations:run-javascript",
}


def _hcl_object(d: dict, indent: str) -> str:
    """Render a flat dict as an HCL object literal for jsonencode(...)."""
    lines = []
    for k, v in d.items():
        val = f'"{v}"' if isinstance(v, str) else ("true" if v is True else "false" if v is False else str(v))
        lines.append(f"{indent}  {k} = {val}")
    return "{\n" + "\n".join(lines) + f"\n{indent}}}"


def render_workflow_tf(spec: AlertSpec) -> str:
    """A `dynatrace_automation_workflow` triggered by this alert's Davis event,
    running one task per notification action. Webhook credentials are referenced,
    never inlined."""
    rname = re.sub(r"[^a-z0-9_]", "_", spec.name.lower()).strip("_") or "alert"
    # NB: the provider block lives in main.tf (same module) — don't repeat it here.
    L: List[str] = [
        "# Workflow for `" + spec.name + "` - fires on the migrated anomaly-detector event and runs",
        "# the original notification actions. Map any webhook auth to a stored Dynatrace",
        "# credential (referenced below, never inlined). Review before enabling.",
        "",
        'resource "dynatrace_automation_workflow" "' + rname + '" {',
        "  title = " + _hcl_str(spec.name + " (migrated)"),
        "  trigger {",
        "    event {",
        "      active = true",
        "      config {",
        "        davis_event {",
        '          custom_filter = "matchesPhrase(event.name, ' + '\\"' + spec.name + '\\")"',
        "        }",
        "      }",
        "    }",
        "  }",
        "  tasks {",
    ]
    actions = spec.actions or [Action("unknown", "notify")]
    for i, a in enumerate(actions):
        action = _ACTION_MAP.get(a.kind, _ACTION_MAP["unknown"])
        if a.kind == "email":
            payload = {"to": a.target, "subject": "[" + spec.name + "] {{event.name}}",
                       "body": "Migrated from Elastic. See the event for details."}
        elif a.kind in ("webhook", "slack"):
            payload = {"method": "POST", "url": "https://" + a.target}
            if a.secret:
                payload["credentialId"] = "REPLACE_WITH_DYNATRACE_CREDENTIAL_ID"
        else:
            payload = {"note": "Original Elastic action `" + a.kind + "` -> review"}
        secret_cmt = ("   // set a Dynatrace credential for `" + a.secret + "`") if a.secret else ""
        L += [
            "    task {",
            '      name     = "' + a.kind + "_" + str(i) + '"',
            '      action   = "' + action + '"' + secret_cmt,
            "      input    = jsonencode(" + _hcl_object(payload, "      ") + ")",
            "      position {",
            "        x = 0",
            "        y = " + str(i),
            "      }",
            "    }",
        ]
    L += ["  }", "}", ""]
    return "\n".join(L)


def needs_workflow(spec: AlertSpec) -> bool:
    from e2d.alerts.model import TARGET_WORKFLOW
    return spec.target == TARGET_WORKFLOW
